spring:
  application:
    name: bit-setup-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bit_setup_server?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: aoyu
  devtools:
    restart:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379       # Redis 端口号
      database: 0      # 使用的数据库索引（默认是 0）
      timeout: 2000    # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 8   # 连接池最大连接数
          max-idle: 8     # 连接池最大空闲连接数
          min-idle: 0     # 连接池最小空闲连接数
  mail:
      host: smtp.qq.com
      port: 587
      username: 339983216@qq.com
      password: whelhgjpovhqcadc
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      default-encoding: UTF-8
  ai:
    openai:
      api-key: AIzaSyB9pZgJ51gvERhSi2Y6Qf3hfj00pV65gDo
      base-url: https://gemini.aoyu925.cn/v1beta/openai
      chat:
        options:
          model: gemini-2.5-flash
          temperature: 0.7


mybatis-plus:
  mapper-locations: classpath*:/com/aoyu/bitsetup/client/mapper/**/*.xml
  type-aliases-package: com.aoyu.bitsetup.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id  # 使用雪花算法ID


knife4j:
  enable: true
springdoc:
  api-docs:
    enabled: true  # 启用 API 文档
  swagger-ui:
    enabled: true  # 启用 Swagger UI

aj:
  captcha:
    jigsaw: classpath:images/jigsaw
    pic-click: classpath:images/pic-click
    cache-type: redis
    type: default
    water-mark: ""
    slip-offset: 5
    aes-status: true
    interference-options: 2
    history-data-clear-enable: false
    req-frequency-limit-enable: false
    req-get-lock-limit: 5
    req-get-lock-seconds: 360
    req-get-minute-limit: 30
    req-check-minute-limit: 70
    req-verify-minute-limit: 80



jwt:
  secret: 32565153813399832160925@bitsetupcreatebyaoyuopfdsjklsdfjsllfdjkfsdfaljhkdsfdsfsd
  expiration: 7d

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: bit-setup
  secure: false